# tasks/apache.yml
# Install and configure Apache for Zabbix web

- name: Install Apache package
  yum:
    name: httpd
    state: installed

- name: Remove autoindex.conf
  file: 
    path: /etc/httpd/conf.d/autoindex.conf
    state: absent

- name: Remove userdir.conf
  file: 
    path: /etc/httpd/conf.d/userdir.conf
    state: absent

- name: Remove welcome.conf
  file: 
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: Copy Apache base config
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'



- name: Create certificate files if needed
  block:
    - name: Copy private key
      copy: 
        content: "{{ zabbix_apache_tls_key_content }}"
        dest: "{{ zabbix_apache_tls_key }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_key_file
    
    - name: Copy certificate
      copy: 
        content: "{{ zabbix_apache_tls_crt_content }}"
        dest: "{{ zabbix_apache_tls_crt }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_cert_file

    - name: Copy certificate chain
      copy: 
        content: "{{ zabbix_apache_tls_chain_content }}"
        dest: "{{ zabbix_apache_tls_chain }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_chain_file

  when: zabbix_apache_web_copy_cop_files

- name: Enable httpd_can_network_connect_db SELinux boolean
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  register: se_bool_httpd_can_network_connect_db

- name: Enable httpd_can_connect_zabbix SELinux boolean
  seboolean:
    name: httpd_can_connect_zabbix
    state: yes
    persistent: yes
  register: se_bool_httpd_can_connect_zabbix

- name: Enable httpd_can_connect_ldap
  seboolean:
    name: httpd_can_connect_ldap
    state: yes
    persistent: yes
  register: se_bool_httpd_can_connect_ldap
  when: zabbix_setsebool_httpd_can_connect_ldap

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes  

- name: Open http port in firewall
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  register: firewall80

- name: Open https port in firewall
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
  register: firewall443

- name: Reload firewall
  command: firewall-cmd --reload
  when: 
    - firewall80 is changed
    - firewall443 is changed
  register: firewallcmdout

- name: Restart httpd service after changes
  service:
    name: httpd
    state: restarted
    enabled: true
  when: 
    - se_bool_httpd_can_network_connect_db is changed
    - se_bool_httpd_can_connect_zabbix is changed
    - se_bool_httpd_can_connect_ldap is changed
    - zabbix_web_tls_crt_file is changed
    - zabbix_web_chain_file is changed
    - zabbix_web_key_file is changed