# tasks/apache.yml
# Install and configure Apache for Zabbix web

- name: Copy Apache Zabbix SSL vhost config
  template:
    src: 10-zabbix.lark-it.com.conf.j2
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/10-zabbix.lark-it.com.conf
    owner: root
    group: root
    mode: '0644'
  register: apache_zabbix_conf

- name: Copy Apache Zabbix non-SSL vhost config
  template:
    src: 10-zabbix.lark-it.com_nonssl.conf.j2
    dest: /opt/rh/httpd24/root/etc/httpd/conf.d/10-zabbix.lark-it.com_nonssl.conf
    owner: root
    group: root
    mode: '0644'
  register: apache_zabbix_nonssl_conf

- name: Create certificate files if needed
  block:
    - name: Ensure key directory exists
      file:
        path: "{{ zabbix_web_tls_key_dir }}"
        owner: root
        group: root
        mode: '0644'
        state: directory
    - name: Ensure certs directory exists
      file:
        path: "{{ zabbix_web_tls_certs_dir }}"
        owner: root
        group: root
        mode: '0644'
        state: directory
    - name: Copy private key
      copy: 
        content: "{{ zabbix_web_tls_key_content }}"
        dest: "{{ zabbix_web_tls_key }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_key_file
    
    - name: Copy certificate
      copy: 
        content: "{{ zabbix_web_tls_cert_content }}"
        dest: "{{ zabbix_web_tls_cert }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_cert_file

    - name: Copy certificate chain
      copy: 
        content: "{{ zabbix_web_tls_chain_content }}"
        dest: "{{ zabbix_web_tls_chain }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_chain_file

  when: zabbix_web_copy_tls_cert_files

- name: Enable httpd_can_network_connect_db SELinux boolean
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: true
  register: se_bool_httpd_can_network_connect_db

- name: Enable httpd_can_connect_zabbix SELinux boolean
  seboolean:
    name: httpd_can_connect_zabbix
    state: yes
    persistent: true
  register: se_bool_httpd_can_connect_zabbix

- name: Enable httpd_can_connect_ldap
  seboolean:
    name: httpd_can_connect_ldap
    state: yes
    persistent: true
  register: se_bool_httpd_can_connect_ldap
  when: zabbix_web_setsebool_httpd_can_connect_ldap

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open http port in firewall
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  register: firewall80

- name: Open https port in firewall
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
  register: firewall443

- name: Reload firewall
  command: firewall-cmd --reload
  when: (firewall80.changed) or (firewall443.changed)
  register: firewallcmdout

- name: Start Apache
  service:
    name: httpd24-httpd
    state: started
    enabled: true

- name: Restart Apache service after changes
  service:
    name: httpd24-httpd
    state: restarted
  when: 
    (se_bool_httpd_can_network_connect_db.changed) or
    (se_bool_httpd_can_connect_zabbix.changed) or
    (se_bool_httpd_can_connect_ldap.changed) or
    (zabbix_web_tls_cert_file.changed) or
    (zabbix_web_tls_chain_file.changed) or
    (zabbix_web_tls_key_file.changed) or
    (apache_zabbix_conf.changed) or
    (apache_zabbix_nonssl_conf.changed)