# tasks/apache.yml
# Install and configure Apache for Zabbix web

- name: Install Apache package
  yum:
    name: httpd
    state: installed

# - name: Remove autoindex.conf
#   file: 
#     path: /etc/httpd/conf.d/autoindex.conf
#     state: absent
#   register: apache_autoindex_conf

# - name: Remove userdir.conf
#   file: 
#     path: /etc/httpd/conf.d/userdir.conf
#     state: absent
#   register: apache_userdir_conf

# - name: Remove welcome.conf
#   file: 
#     path: /etc/httpd/conf.d/welcome.conf
#     state: absent
#   register: apache_welcome_conf

# - name: Copy Apache base config
#   template:
#     src: httpd.conf.j2
#     dest: /etc/httpd/conf/httpd.conf
#     owner: root
#     group: root
#     mode: '0644'
#   register: apache_httpd_conf

# - name: Copy Apache SSL config
#   template:
#     src: ssl.conf.j2
#     dest: /etc/httpd/conf.d/ssl.conf.j2
#     owner: root
#     group: root
#     mode: '0644'
#   register: apache_ssl_conf

- name: Copy Apache Zabbix SSL vhost config
  template:
    src: 10-zabbix.lark-it.com.conf.j2
    dest: /etc/httpd/conf.d/10-zabbix.lark-it.com.conf.j2
    owner: root
    group: root
    mode: '0644'
  register: apache_zabbix_conf

- name: Copy Apache Zabbix non-SSL vhost config
  template:
    src: 10-zabbix.lark-it.com_nonssl.conf.j2
    dest: /etc/httpd/conf.d/10-zabbix.lark-it.com_nonssl.conf.j2
    owner: root
    group: root
    mode: '0644'
  register: apache_zabbix_nonssl_conf

- name: Create certificate files if needed
  block:
    - name: Copy private key
      copy: 
        content: "{{ zabbix_web_tls_key_content }}"
        dest: "{{ zabbix_web_tls_key }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_key_file
    
    - name: Copy certificate
      copy: 
        content: "{{ zabbix_web_tls_cert_content }}"
        dest: "{{ zabbix_web_tls_cert }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_cert_file

    - name: Copy certificate chain
      copy: 
        content: "{{ zabbix_web_tls_chain_content }}"
        dest: "{{ zabbix_web_tls_chain }}"
        owner: apache
        group: apache
        mode: 0600
      register: zabbix_web_tls_chain_file

  when: zabbix_web_copy_tls_cert_files

- name: Enable httpd_can_network_connect_db SELinux boolean
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: true
  register: se_bool_httpd_can_network_connect_db

- name: Enable httpd_can_connect_zabbix SELinux boolean
  seboolean:
    name: httpd_can_connect_zabbix
    state: yes
    persistent: true
  register: se_bool_httpd_can_connect_zabbix

- name: Enable httpd_can_connect_ldap
  seboolean:
    name: httpd_can_connect_ldap
    state: yes
    persistent: true
  register: se_bool_httpd_can_connect_ldap
  when: zabbix_web_setsebool_httpd_can_connect_ldap

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Open http port in firewall
  firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
  register: firewall80

- name: Open https port in firewall
  firewalld:
    port: 443/tcp
    permanent: true
    state: enabled
  register: firewall443

- name: Reload firewall
  command: firewall-cmd --reload
  when: 
    - firewall80.changed
    - firewall443.changed
  register: firewallcmdout

- name: Start Apache
  service:
    name: httpd
    state: started
    enabled: true

- name: Restart Apache service after changes
  service:
    name: httpd
    state: restarted
  when: 
    - apache_zabbix_conf.changed
    - apache_zabbix_nonssl_conf.changed
    
    # - se_bool_httpd_can_network_connect_db.changed
    # - se_bool_httpd_can_connect_zabbix.changed
    # - se_bool_httpd_can_connect_ldap.changed
    # - zabbix_web_tls_crt_file.changed
    # - zabbix_web_chain_file.changed
    # - zabbix_web_key_file.changed
    # - apache_autoindex_conf is changed
    # - apache_userdir_conf is changed
    # - apache_welcome_conf is changed
    # - apache_httpd_conf is changed
    # - apache_ssl_conf is changed
    # - apache_zabbix_conf.changed
    # - apache_zabbix_nonssl_conf.changed