---
# tasks/main.yml
# Configure Zabbix web frontend

- name: Ensure that extra packages are installed
  yum:
    name: 
     - policycoreutils-python
     - firewalld
     - python-firewall
     - yum-utils
     - centos-release-scl # Modern PHP releases
    state: installed

- name: Install Zabbix repo CentOS 7
  block:
    - name: Install Zabbix repo package
      yum:
        name:
          - https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    
    - name: Enable Zabbix web repo
      shell: /bin/yum-config-manager --enable zabbix-frontend
  
  when: zabbix_web_manage_repos

- name: Install Zabbix web package
  yum: 
    name: 
      - zabbix-web-mysql-scl

# - name: Install PHP
#   include_tasks: php.yml

- name: Install httpd
  include_tasks: apache.yml
