---
# tasks/main.yml
# Configure Zabbix web frontend

- name: Install Zabbix repo CentOS 7
  block:
    - name: Install Zabbix repo package
      yum:
        name:
          - https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    
    - name: Enable Zabbix web repo
      shell: /bin/yum-config-manager --enable zabbix-frontend && touch /etc/zabbix/.web_repo_enabled
      args:
        creates: /etc/zabbix/.web_repo_enabled
  
  when: zabbix_web_manage_repos

- name: Install SCL Repo
  yum: 
    name: 
     - centos-release-scl
    state: installed

- name: Install required packages
  yum:
    name: 
     - policycoreutils-python
     - firewalld
     - python-firewall
     - yum-utils
     - rh-php72-php # httpd24-httpd is a dependency
     - httpd24-mod_ssl
     - zabbix-web-mysql-scl
    state: installed

- name: Install httpd
  include_tasks: apache.yml

- name: Install Zabbix web config file
  template:
    src: zabbix.conf.php.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: apache
    group: apache
    mode: '0640'
  register: zabbix_web_conf

- name: Restart Apache service after changes
  service:
    name: httpd24-httpd
    state: restarted
  when: zabbix_web_conf.changed

- name: Delete setup.php for security
  file: 
    path: /usr/share/zabbix/setup.php
    state: absent

- name: Copy SAML idp certificate
  copy:
    src: idp.crt
    dest: /usr/share/zabbix/conf/certs/idp.crt
  when: zabbix_web_saml_config