---
# tasks/main.yml
# Configure Zabbix web frontend

- name: Ensure that extra packages are installed
  yum:
    name: 
     - policycoreutils-python
     - firewalld
     - python-firewall
     - httpd
    state: installed

- name: Install Zabbix repo CentOS 7
  yum_repository:
    name: zabbix
    description: "Zabbix Official Repository - $basearch" 
    file: zabbix
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
    gpgcheck: true
  when: zabbix_web_manage_repos

- name: Create certificate files if needed
  block:
    - name: Copy private key
      copy: 
        content: "{{ zabbix_apache_tls_key_content }}"
        dest: "{{ zabbix_apache_tls_key }}"
        owner: apache
        group: apache
        mode: 0600
      register: apache_tls_key_file
    
    - name: Copy certificate
      copy: 
        content: "{{ zabbix_apache_tls_crt_content }}"
        dest: "{{ zabbix_apache_tls_crt }}"
        owner: apache
        group: apache
        mode: 0600
      register: apache_tls_crt_file

    - name: Copy certificate chain
      copy: 
        content: "{{ zabbix_apache_tls_chain_content }}"
        dest: "{{ zabbix_apache_tls_chain }}"
        owner: apache
        group: apache
        mode: 0600
      register: apache_tls_chain_file

  when: zabbix_apache_tls_copy_crt_files

- name: Install PHP
  include_tasks: php.yml

# - name: Install httpd

- name: Enable httpd_can_network_connect_db SELinux boolean
  seboolean:
    name: httpd_can_network_connect_db
    state: yes
    persistent: yes
  register: se_bool_httpd_can_network_connect_db

- name: Enable httpd_can_connect_zabbix SELinux boolean
  seboolean:
    name: httpd_can_connect_zabbix
    state: yes
    persistent: yes
  register: se_bool_httpd_can_connect_zabbix

- name: Enable httpd_can_connect_ldap
  seboolean:
    name: httpd_can_connect_ldap
    state: yes
    persistent: yes
  register: se_bool_httpd_can_connect_ldap
  when: zabbix_setsebool_httpd_can_connect_ldap

- name: Start firewalld service
  service:
    name: firewalld
    state: started
    enabled: yes  

- name: Open http port in firewall
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  register: firewall80

- name: Open https port in firewall
  firewalld:
    port: 443/tcp
    permanent: yes
    state: enabled
  register: firewall443

- name: Reload firewall
  command: firewall-cmd --reload
  when: 
    - firewall80 is changed
    - firewall443 is changed
  register: firewallcmdout

- name: Restart httpd service after changes
  service:
    name: httpd
    state: restarted
    enabled: true
  when: 
    - se_bool_httpd_can_network_connect_db is changed
    - se_bool_httpd_can_connect_zabbix is changed
    - se_bool_httpd_can_connect_ldap is changed
    - apache_tls_crt_file is changed
    - apache_tls_chain_file is changed
    - apache_tls_key_file is changed