---
# tasks/php.yml
# Install and configure PHP for Zabbix web

- name: Install repos if needed
  block:
    - name: Install PHP repos
      yum:
        name: 
          - epel-release
          - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: installed
    
    - name: Enable PHP repo
      shell: /bin/yum-config-manager --enable remi-php73 && touch /etc/yum.repos.d/.remi_php_enabled
      args:
        creates: /etc/yum.repos.d/.remi_php_enabled
  
  when: zabbix_web_manage_repos

- name: Install PHP
  yum:
    name:
     - php
     - php-mysqlnd
    state: installed

- name: Configure PHP
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: '0644'